- platform: gpio
  name: "Relé 1"
  id: rele1
  pin:
    sn74hc595: sn74hc595_hub
    number: 0
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 2"
  id: rele2
  pin:
    sn74hc595: sn74hc595_hub
    number: 1
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 3"
  id: rele3
  pin:
    sn74hc595: sn74hc595_hub
    number: 2
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 4"
  id: rele4
  pin:
    sn74hc595: sn74hc595_hub
    number: 3
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 5"
  id: rele5
  pin:
    sn74hc595: sn74hc595_hub
    number: 4
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 6"
  id: rele6
  pin:
    sn74hc595: sn74hc595_hub
    number: 5
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 7"
  id: rele7
  pin:
    sn74hc595: sn74hc595_hub
    number: 6
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 8"
  id: rele8
  pin:
    sn74hc595: sn74hc595_hub
    number: 7
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 9"
  id: rele9
  pin:
    sn74hc595: sn74hc595_hub
    number: 8
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 10"
  id: rele10
  pin:
    sn74hc595: sn74hc595_hub
    number: 9
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 11"
  id: rele11
  pin:
    sn74hc595: sn74hc595_hub
    number: 10
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 12"
  id: rele12
  pin:
    sn74hc595: sn74hc595_hub
    number: 11
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 13"
  id: rele13
  pin:
    sn74hc595: sn74hc595_hub
    number: 12
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 14"
  id: rele14
  pin:
    sn74hc595: sn74hc595_hub
    number: 13
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 15"
  id: rele15
  pin:
    sn74hc595: sn74hc595_hub
    number: 14
  restore_mode: RESTORE_DEFAULT_ON

- platform: gpio
  name: "Relé 16"
  id: rele16
  pin:
    sn74hc595: sn74hc595_hub
    number: 15
  restore_mode: RESTORE_DEFAULT_ON